# Generated by Django 3.2.5 on 2021-08-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'ویدیو', 'verbose_name_plural': 'ویدیوها'},
        ),
    ]
