# Generated by Django 3.2.5 on 2021-09-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_video_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(default=None, verbose_name='درباره نقاشی'),
        ),
    ]
