# Generated by Django 3.2.5 on 2021-09-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_gallery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='درباره نقاشی'),
        ),
    ]
