# Generated by Django 3.2.5 on 2021-07-28 18:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیمات', 'verbose_name_plural': 'بیوگرافی و ارتباط با ما'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='بیوگرافی هنرمند'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='ارتباط با ما'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
